before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Freshchris01"
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
github-token: $GITHUB_TOKEN 
provider: pages
script:
  - npm run deploy