before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Freshchris01"
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
script:
  - npm run deploy
